apiVersion: v1
kind: Secret
metadata:
  name: minha-app-secrets
  namespace: default
type: Opaque
stringData:
  CLASS_NAME: "${{ secrets.CLASS_NAME }}"
  DATA_BASE_URL: "${{ secrets.DATA_BASE_URL }}"
  HIBERNATE_DIALECT: "${{ secrets.HIBERNATE_DIALECT }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  USER_NAME: "${{ secrets.USER_NAME }}"
  PORT_SERVER: "${{ secrets.PORT_SERVER }}"
