name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CLASS_NAME: ${{ secrets.CLASS_NAME }}
      DATA_BASE_URL: ${{ secrets.DATA_BASE_URL }}
      HIBERNATE_DIALECT: ${{ secrets.HIBERNATE_DIALECT }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PORT_SERVER: ${{ secrets.PORT_SERVER }}
      USER_NAME: ${{ secrets.USER_NAME }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Build da imagem
        run: |
          docker build \
            --build-arg CLASS_NAME=$CLASS_NAME \
            --build-arg DATA_BASE_URL=$DATA_BASE_URL \
            --build-arg HIBERNATE_DIALECT=$HIBERNATE_DIALECT \
            --build-arg PASSWORD=$PASSWORD \
            --build-arg USER_NAME=$USER_NAME \
            --build-arg PORT_SERVER=$PORT_SERVER \
          
            -t ghcr.io/${{ github.repository_owner }}/minha-app:latest .

      - name: Push da imagem
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/minha-app:latest